from db.mongodb import db
from bson import ObjectId

# Alert schema: generated by machines, visible to patient and doctor
# Example alert: { _id, device_id, patient_id, doctor_id, type, message, timestamp, seen_by_patient, seen_by_doctor }
alerts = db.alerts

# Alert CRUD

def create_alert(alert):
    return alerts.insert_one(alert)

def get_alert_by_id(alert_id):
    return alerts.find_one({'_id': ObjectId(alert_id)})

def get_alerts_by_patient(patient_id):
    return list(alerts.find({'patient_id': patient_id}))

def get_alerts_by_doctor(doctor_id):
    return list(alerts.find({'doctor_id': doctor_id}))

def update_alert(alert_id, update):
    return alerts.update_one({'_id': ObjectId(alert_id)}, {'$set': update})

def delete_alert(alert_id):
    return alerts.delete_one({'_id': ObjectId(alert_id)})
